In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("laptops_analysis.csv")
df

,Product Name,Processor,RAM,SSD,Display,Price,Discount,Rating,Price_After_Discount,Price_Category,Screen_Type,Rating_Category,Brand
0,HP Chromebook MediaTek Kompanio 540 - (4 GB/12...,Kompanio,4,128 GB,35.56,36990.0,37,4.5,23303.70,Budget,Standard,Excellent,HP
1,HP Chromebook (TouchScreen) MediaTek Kompanio ...,Kompanio,4,128 GB,35.56,39990.0,40,3.8,23994.00,Budget,Standard,Average,HP
2,Acer Aspire 15 Lite(i5 14th Gen) Intel Core 5 ...,Intel,16,512 GB,39.62,59990.0,24,4.4,45592.40,Premium,Standard,Excellent,Acer
3,Ultimus Apex Pro Intel Pentium Quad Core N4200...,Intel,4,128 GB,35.81,19990.0,28,3.3,14392.80,Budget,Standard,Average,Ultimus
4,WarnerCann N95 Notebook Intel Core N 12th Gen ...,Intel,12,256 GB,38.86,22318.0,41,4.2,13167.62,Budget,Standard,Excellent,WarnerCann
...,...,...,...,...,...,...,...,...,...,...,...,...,...
721,Lenovo Legion 5 2025 Intel Core i7 13650HX - (...,Intel,16,1 TB,38.86,185490.0,11,4.0,165086.10,Premium,Standard,Average,Lenovo
722,Samsung Galaxy Book4 360 Evo (i7 14th Gen) Int...,Intel,16,512 GB,39.62,109899.0,22,4.2,85721.22,Premium,Standard,Excellent,Samsung
723,Lenovo LOQ AMD Ryzen 5 Quad Core 7235HS - (24 ...,AMD,24,512 GB,39.62,77990.0,22,4.4,60832.20,Premium,Standard,Excellent,Lenovo
724,Acer 1305U Intel Core i3 13th Gen 1305U - (8 G...,Intel,8,512 GB,39.62,68990.0,13,4.2,60021.30,Premium,Standard,Excellent,Acer
725,Samsung Galaxy Book6 Intel Core Ultra 5 Series...,Intel,16,512 GB,35.56,112990.0,20,4.2,90392.00,Premium,Standard,Excellent,Samsung

#### 1. Which laptop brand has the highest number of models?

In [3]:
df["Brand"].value_counts()

Brand
HP            194
ASUS          174
Lenovo        101
Acer           88
DELL           72
MSI            31
Samsung        24
MICROSOFT      11
Infinix        10
Apple           6
Primebook       4
MOTOROLA        4
ZEBRONICS       3
Ultimus         1
WarnerCann      1
Colorful        1
Avita           1
Name: count, dtype: int64

##### The brand with the highest number of laptop models has the strongest product presence in the market and offers customers more choices.

#### 2. Which processor company is most popular?

In [4]:
df["Processor"].value_counts()

Processor
Intel         503
AMD           180
Snapdragon     30
Kompanio        7
Apple           6
Name: count, dtype: int64

##### The processor company with the highest count is the most preferred by laptop manufacturers in the dataset.

#### 3. What is the average price of laptops for each brand?

In [5]:
df.groupby("Brand")["Price"].mean().sort_values(ascending=False)

Brand
Apple         191566.666667
MICROSOFT     156130.272727
Colorful      139999.000000
Samsung       134947.000000
MSI           122418.322581
Lenovo        102909.740000
ASUS           98680.695402
DELL           83503.500000
MOTOROLA       76490.000000
HP             73842.580311
ZEBRONICS      72999.000000
Infinix        69440.900000
Acer           68136.590909
Avita          60990.000000
Primebook      30490.000000
WarnerCann     22318.000000
Ultimus        19990.000000
Name: Price, dtype: float64

##### Brands with higher average prices mainly target premium customers, while lower-priced brands focus on budget-conscious buyers.

#### 4. Which RAM capacity is most common?

In [6]:
df["RAM"].value_counts()

RAM
16     389
8      236
32      49
24      25
4       14
12       9
64       2
128      1
36       1
Name: count, dtype: int64

##### The most common RAM configuration indicates the current market standard for laptops.

#### 5. Which SSD storage capacity is most popular?

In [7]:
df["SSD"].value_counts()

SSD
512 GB    551
1 TB      128
256 GB     32
2 TB       10
128 GB      5
Name: count, dtype: int64

##### The most frequently available SSD capacity reflects customer demand and manufacturer preferences.

#### 6. Which brands offer the highest average discount?

In [8]:
df.groupby("Brand")["Discount"].mean().round(2).sort_values(ascending=False)

Brand
WarnerCann    41.00
ZEBRONICS     40.00
Apple         40.00
Colorful      40.00
Avita         40.00
Infinix       38.20
MOTOROLA      32.75
Primebook     31.50
Ultimus       28.00
Samsung       26.58
MICROSOFT     26.18
Acer          23.24
ASUS          22.39
Lenovo        22.21
MSI           21.61
HP            19.00
DELL          18.43
Name: Discount, dtype: float64

##### Brands providing higher average discounts are likely using promotional pricing to attract more customers.

#### 7. How many Budget and Premium laptops are available?

In [9]:
df["Price_Category"].value_counts()

Price_Category
Premium    605
Budget     121
Name: count, dtype: int64

##### This helps understand whether the market is dominated by budget laptops or premium laptops.

#### 8. Which processor company has the highest average laptop price?

In [10]:
df.groupby("Processor")["Price"].mean().round(2).sort_values(ascending=False)

Processor
Apple         191566.67
Snapdragon    108398.60
Intel          93795.54
AMD            75543.87
Kompanio       30805.43
Name: Price, dtype: float64

##### This comparison shows which processor brands are commonly used in premium-priced laptops.

#### 9. Which are the Top 10 most expensive laptops?

In [11]:
df[["Product Name","Brand","Price"]].sort_values(
    by="Price",
    ascending=False
).head(10)

                                          Product Name  Brand     Price
491  DELL Alienware Intel Core Ultra 9 185H - (32 G...   DELL  572317.0
585  MSI Titan GT77 Intel Core i9 13th Gen 13980HX ...    MSI  548990.0
351  Apple MacBook Pro (M5 Max, 2026) M5 Max - (36 ...  Apple  539900.0
113  ASUS ROG Zephyrus G16 OLED (2026) Intel Core U...   ASUS  507156.0
7    ASUS ROG Zephyrus G16 OLED (2026) Intel Core U...   ASUS  499990.0
692  ASUS ROG Zephyrus M16 with 90Whr Battery Intel...   ASUS  395990.0
704  DELL XPS Intel Core Ultra 7 155H - (32 GB/1 TB...   DELL  385830.0
337  ASUS ROG Strix SCAR 16 (2025) with Office 2024...   ASUS  369990.0
520  ASUS ROG Zephyrus G16 (2025) with Office 2024 ...   ASUS  360358.0
280  ASUS ExpertBook Ultra Copilot+ PC Intel Core U...   ASUS  349990.0

##### These laptops represent the premium segment and usually include high-end specifications and advanced features.

#### 10. Which brands have the highest average ratings?

In [12]:
df.groupby("Brand")["Rating"].mean().round(1).sort_values(ascending=False)

Brand
Apple         4.6
Primebook     4.4
MOTOROLA      4.4
ASUS          4.3
Avita         4.3
Samsung       4.3
MSI           4.3
Colorful      4.2
Lenovo        4.2
WarnerCann    4.2
HP            4.1
DELL          4.1
Acer          4.1
MICROSOFT     4.1
Infinix       4.0
ZEBRONICS     4.0
Ultimus       3.3
Name: Rating, dtype: float64

##### Brands with higher average ratings generally receive better customer satisfaction and positive reviews.